import http from 'node:http';
import net from 'node:net';
import os from 'node:os';
import crypto from 'node:crypto';

const PORT=Number(process.env.FINGERPRINT_GATEWAY_PORT||8787);
const HOST=process.env.FINGERPRINT_GATEWAY_HOST||'0.0.0.0';

function localSubnets(){const out=[];for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(!n.internal&&n.family==='IPv4'){const p=n.address.split('.');out.push(p.slice(0,3).join('.'));}return [...new Set(out)];}
function tcpOpen(ip,port,timeout=700){return new Promise(resolve=>{const s=new net.Socket();let done=false;const finish=v=>{if(done)return;done=true;s.destroy();resolve(v)};s.setTimeout(timeout);s.once('connect',()=>finish(true));s.once('timeout',()=>finish(false));s.once('error',()=>finish(false));s.connect(port,ip);});}
async function probe(ip,port){return tcpOpen(ip,port).then(ok=>ok?{ip,port}:null);}
async function discover(){const subs=localSubnets();const ports=[4370,80,443,8080,8000,8081,8443,9000,37777];const found=[];for(const subnet of subs){const jobs=[];for(let h=1;h<=254;h++)for(const port of ports)jobs.push(probe(subnet+'.'+h,port));for(let i=0;i<jobs.length;i+=80){const part=await Promise.all(jobs.slice(i,i+80));found.push(...part.filter(Boolean));}}const byIp=new Map();for(const x of found){const key=x.ip+'|'+x.port;if(!byIp.has(key))byIp.set(key,{...x,protocol:x.port===4370?'zk':x.port===8000?'hikvision':'http',name:x.port===4370?'ZK-compatible biometric device':x.port===8000?'Hikvision candidate':'HTTP biometric device',source:'LAN TCP discovery'});}return [...byIp.values()];}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',x=>s+=x);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});});}
async function pullGenericHttp(d){const protocol=Number(d.port)===443||Number(d.port)===8443?'https':'http';const base=protocol+'://'+d.ip+':'+(Number(d.port)||80);const paths=['/api/attendance','/api/records','/ISAPI/AccessControl/AcsEvent'];const auth=d.username?Buffer.from(String(d.username)+':'+String(d.password||'')).toString('base64'):'';for(const path of paths){try{const r=await fetch(base+path,{headers:auth?{Authorization:'Basic '+auth}:{} });if(!r.ok)continue;const j=await r.json();const arr=j.records||j.data||j.Attendance||j.AcsEvent?.InfoList||[];if(!Array.isArray(arr))continue;const punches=arr.map(x=>{const code=String(x.code??x.pin??x.user_id??x.employeeNoString??x.employeeNo??'').trim();const dt=new Date(x.datetime??x.timestamp??x.time??x.dateTime??'');if(!code||Number.isNaN(dt.getTime()))return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:String(x.name??x.user_name??''),date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5)}}).filter(Boolean);return punches;}catch{}}throw new Error('لم يتم التعرف على API قياسي لهذا الجهاز');}
async function testZk(d){let Zkteco;try{({default:Zkteco}=await import('zkteco-js'));}catch{return {ok:false,message:'Driver zkteco-js غير مثبت داخل admin-affairs.'};}const client=new Zkteco(d.ip,Number(d.port)||4370,5000,5000);try{await client.createSocket();return {ok:true,message:'تم الاتصال بجهاز ZKTeco عبر ZKProtocol على TCP '+(Number(d.port)||4370)};}catch(e){return {ok:false,message:'المنفذ مفتوح لكن اتصال ZKProtocol فشل: '+(e instanceof Error?e.message:String(e))};}finally{try{await client.disconnect()}catch{}}}
async function testDevice(d){if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))return testZk(d);const ok=await tcpOpen(d.ip,Number(d.port)||80,1200);return {ok,message:ok?'منفذ HTTP متاح':'منفذ الجهاز غير متاح'};}

function decodeZkText(value){const s=String(value??'').replace(/\u0000/g,'').trim();if(!s)return '';if(/[\u0600-\u06ff]/.test(s))return s;try{const bytes=Buffer.from(s,'latin1');const decoded=bytes.toString('win1256');if(/[\u0600-\u06ff]/.test(decoded))return decoded.replace(/\u0000/g,'').trim();}catch{}return s;}
function unwrapRows(value){if(Array.isArray(value))return value;if(value&&Array.isArray(value.data))return value.data;if(value&&Array.isArray(value.records))return value.records;if(value&&Array.isArray(value.attendances))return value.attendances;return [];}
function dateParts(value){if(value instanceof Date&&!Number.isNaN(value.getTime()))return {date:value.toISOString().slice(0,10),time:value.toTimeString().slice(0,5)};const s=String(value??'').trim();if(!s)return null;const m=s.match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})[ T](\d{1,2}):(\d{2})(?::(\d{2}))?/);if(m)return {date:`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`,time:`${String(m[4]).padStart(2,'0')}:${m[5]}`};const d=new Date(s);if(Number.isNaN(d.getTime()))return null;return {date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5)};}
function normalizeZkLog(x,userMap){const raw=x||{};const uid=String(raw.uid??raw.userSn??'').trim();const userId=String(raw.user_id??raw.userId??raw.userid??raw.deviceUserId??raw.id??'').trim();const user=userMap.get(uid)||userMap.get(userId);const code=String(user?.userId??user?.userid??userId??uid).trim();const stamp=raw.timestamp??raw.record_time??raw.recordTime??raw.time??raw.attTime??raw.datetime;const parts=dateParts(stamp);if(!code||!parts)return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:decodeZkText(user?.name??raw.user_name??raw.name??''),date:parts.date,time:parts.time};}
async function pullZk(d){let Zkteco;try{({default:Zkteco}=await import('zkteco-js'));}catch{throw new Error('Driver ZKTeco غير مثبت. نفّذ npm install zkteco-js داخل admin-affairs.')}const device=new Zkteco(d.ip,Number(d.port)||4370,10000,10000);try{await device.createSocket();const rawUsers=unwrapRows(await device.getUsers());const userMap=new Map();for(const u of rawUsers){const uid=String(u.uid??'').trim();const userId=String(u.userId??u.userid??u.pin??'').trim();const normalized={...u,name:decodeZkText(u.name??u.username??'')};if(uid)userMap.set(uid,normalized);if(userId)userMap.set(userId,normalized);}const rawLogs=unwrapRows(await device.getAttendances());const punches=rawLogs.map(x=>normalizeZkLog(x,userMap)).filter(Boolean);if(!punches.length&&rawLogs.length)throw new Error('تم الاتصال بالجهاز وقراءة السجلات، لكن لم يمكن تحويل حقول السجل إلى رقم موظف وتاريخ/وقت. تم إيقاف الحفظ لمنع تقرير حضور خاطئ.');return punches;}finally{try{await device.disconnect()}catch{}}}
async function pullHik(d){const auth=Buffer.from(String(d.username||'')+':'+String(d.password||'')).toString('base64');const now=new Date();const start=new Date(now.getTime()-7*86400000);const url='http://'+d.ip+':'+(Number(d.port)||80)+'/ISAPI/AccessControl/AcsEvent?format=json';const payload={AcsEventCond:{searchID:crypto.randomUUID(),searchResultPosition:0,maxResults:1000,major:5,minor:0,startTime:start.toISOString(),endTime:now.toISOString()}};const r=await fetch(url,{method:'POST',headers:{Authorization:'Basic '+auth,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Hikvision HTTP '+r.status);const j=await r.json();const list=j?.AcsEvent?.InfoList||j?.AcsEvent?.AcsEventInfo||[];return (Array.isArray(list)?list:[list]).map(x=>{const code=String(x.employeeNoString??x.employeeNo??'').trim();const dt=new Date(x.time||x.dateTime||'');if(!code||Number.isNaN(dt.getTime()))return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:String(x.name||''),date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5)}}).filter(Boolean);}
async function pullZkUsers(d){let Zkteco;try{({default:Zkteco}=await import('zkteco-js'));}catch{throw new Error('Driver ZKTeco غير مثبت. نفّذ npm install داخل admin-affairs.')}const client=new Zkteco(d.ip,Number(d.port)||4370,10000,10000);try{await client.createSocket();const result=await client.getUsers();const rows=unwrapRows(result);return rows.map(x=>({pin:String(x.userId??x.userid??x.uid??x.pin??''),name:decodeZkText(x.name??x.username??''),card:String(x.cardno??x.cardNo??'')})).filter(x=>x.pin||x.name)}finally{try{await client.disconnect()}catch{}}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS')return json(res,204,{});if(u.pathname==='/api/fingerprint/health')return json(res,200,{ok:true,port:PORT});if(u.pathname==='/api/fingerprint/discover')return json(res,200,{devices:await discover()});if(u.pathname==='/api/fingerprint/test'){const r=await testDevice({ip:u.searchParams.get('ip'),port:Number(u.searchParams.get('port')||4370),protocol:u.searchParams.get('protocol')||'auto'});return json(res,r.ok?200:502,r);}if(u.pathname==='/api/fingerprint/users'&&req.method==='POST'){const d=await body(req);if(!d?.ip)throw new Error('device is required');if(d.protocol==='zk'||d.protocol==='auto')return json(res,200,{users:await pullZkUsers(d)});throw new Error('استيراد المستخدمين متاح حاليًا لـ ZKTeco');}if(u.pathname==='/api/fingerprint/pull'&&req.method==='POST'){const d=await body(req);let punches=[];if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))punches=await pullZk(d);else if(d.protocol==='hikvision')punches=await pullHik(d);else if(d.protocol==='http'||d.protocol==='auto')punches=await pullGenericHttp(d);else throw new Error('لا يوجد Driver لهذا البروتوكول حتى الآن');return json(res,200,{punches,count:punches.length});}return json(res,404,{message:'Not found'});}catch(e){return json(res,500,{ok:false,message:e instanceof Error?e.message:String(e)})}});
server.listen(PORT,HOST,()=>console.log(`Fingerprint Gateway listening on http://${HOST}:${PORT}`));
