import http from 'node:http';
import net from 'node:net';
import os from 'node:os';
import crypto from 'node:crypto';
import Zkteco from 'zkteco-js';

const PORT=Number(process.env.FINGERPRINT_GATEWAY_PORT||8787);
const HOST=process.env.FINGERPRINT_GATEWAY_HOST||'0.0.0.0';

function localSubnets(){const out=[];for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(!n.internal&&n.family==='IPv4'){const p=n.address.split('.');out.push(p.slice(0,3).join('.'));}return [...new Set(out)];}
function tcpOpen(ip,port,timeout=350){return new Promise(resolve=>{const s=new net.Socket();let done=false;const finish=v=>{if(done)return;done=true;s.destroy();resolve(v)};s.setTimeout(timeout);s.once('connect',()=>finish(true));s.once('timeout',()=>finish(false));s.once('error',()=>finish(false));s.connect(port,ip);});}
async function probe(ip,port){return tcpOpen(ip,port).then(ok=>ok?{ip,port}:null);}
async function discover(){const subs=localSubnets();const ports=[4370,80,443,8080,8000];const found=[];for(const subnet of subs){const jobs=[];for(let h=1;h<=254;h++)for(const port of ports)jobs.push(probe(subnet+'.'+h,port));for(let i=0;i<jobs.length;i+=80){const part=await Promise.all(jobs.slice(i,i+80));found.push(...part.filter(Boolean));}}const byIp=new Map();for(const x of found){const key=x.ip+'|'+x.port;if(!byIp.has(key))byIp.set(key,{...x,protocol:x.port===4370?'zk':'http',name:x.port===4370?'ZK-compatible biometric device':'HTTP device',source:'LAN TCP discovery'});}return [...byIp.values()];}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',x=>s+=x);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});});}
async function testDevice(d){if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370)){const ok=await tcpOpen(d.ip,Number(d.port)||4370,900);return {ok,message:ok?'منفذ ZK متاح':'منفذ الجهاز غير متاح'};}const ok=await tcpOpen(d.ip,Number(d.port)||80,900);return {ok,message:ok?'منفذ HTTP متاح':'منفذ الجهاز غير متاح'};}
function normalizeZkLog(x){const raw=x||{};const code=String(raw.user_id??raw.uid??raw.userid??raw.id??'').trim();const dt=new Date(raw.timestamp??raw.record_time??raw.time??'');if(!code||Number.isNaN(dt.getTime()))return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:String(raw.user_name??raw.name??''),date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5)};}
async function pullZk(d){const device=new Zkteco(d.ip,Number(d.port)||4370,5000,5000);try{await device.createSocket();const logs=await device.getAttendances();return logs.map(normalizeZkLog).filter(Boolean);}finally{try{await device.disconnect()}catch{}}}
async function pullHik(d){const auth=Buffer.from(String(d.username||'')+':'+String(d.password||'')).toString('base64');const now=new Date();const start=new Date(now.getTime()-7*86400000);const url='http://'+d.ip+':'+(Number(d.port)||80)+'/ISAPI/AccessControl/AcsEvent?format=json';const payload={AcsEventCond:{searchID:crypto.randomUUID(),searchResultPosition:0,maxResults:1000,major:5,minor:0,startTime:start.toISOString(),endTime:now.toISOString()}};const r=await fetch(url,{method:'POST',headers:{Authorization:'Basic '+auth,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Hikvision HTTP '+r.status);const j=await r.json();const list=j?.AcsEvent?.InfoList||j?.AcsEvent?.AcsEventInfo||[];return (Array.isArray(list)?list:[list]).map(x=>{const code=String(x.employeeNoString??x.employeeNo??'').trim();const dt=new Date(x.time||x.dateTime||'');if(!code||Number.isNaN(dt.getTime()))return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:String(x.name||''),date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5)}}).filter(Boolean);}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS')return json(res,204,{});if(u.pathname==='/api/fingerprint/discover')return json(res,200,{devices:await discover()});if(u.pathname==='/api/fingerprint/test'){const r=await testDevice({ip:u.searchParams.get('ip'),port:Number(u.searchParams.get('port')||4370),protocol:u.searchParams.get('protocol')||'auto'});return json(res,200,r);}if(u.pathname==='/api/fingerprint/pull'&&req.method==='POST'){const d=await body(req);let punches=[];if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))punches=await pullZk(d);else if(d.protocol==='hikvision')punches=await pullHik(d);else throw new Error('لا يوجد Driver لهذا البروتوكول حتى الآن');return json(res,200,{punches,count:punches.length});}return json(res,404,{message:'Not found'});}catch(e){return json(res,500,{ok:false,message:e instanceof Error?e.message:String(e)})}});
server.listen(PORT,HOST,()=>console.log(`Fingerprint Gateway listening on http://${HOST}:${PORT}`));
