import http from 'node:http';
import net from 'node:net';
import os from 'node:os';
import crypto from 'node:crypto';

const PORT=Number(process.env.FINGERPRINT_GATEWAY_PORT||8787);
const HOST=process.env.FINGERPRINT_GATEWAY_HOST||'0.0.0.0';
const ZK_USERS=Buffer.from([0x01,0x09,0x00,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x00]);
const ZK_ATT=Buffer.from([0x01,0x0d,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00]);

function localSubnets(){const out=[];for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(!n.internal&&n.family==='IPv4'){const p=n.address.split('.');out.push(p.slice(0,3).join('.'));}return [...new Set(out)];}
function tcpOpen(ip,port,timeout=700){return new Promise(resolve=>{const s=new net.Socket();let done=false;const finish=v=>{if(done)return;done=true;s.destroy();resolve(v)};s.setTimeout(timeout);s.once('connect',()=>finish(true));s.once('timeout',()=>finish(false));s.once('error',()=>finish(false));s.connect(port,ip);});}
async function probe(ip,port){return tcpOpen(ip,port).then(ok=>ok?{ip,port}:null);}
async function discover(onlyPort){const subs=localSubnets(),ports=onlyPort?[Number(onlyPort)]:[4370,80,443,8080,8000,8081,8443,9000,37777],found=[];for(const subnet of subs){const jobs=[];for(let h=1;h<=254;h++)for(const port of ports)jobs.push(probe(subnet+'.'+h,port));for(let i=0;i<jobs.length;i+=80)found.push(...(await Promise.all(jobs.slice(i,i+80))).filter(Boolean));}const byIp=new Map();for(const x of found){const key=x.ip+'|'+x.port;if(!byIp.has(key))byIp.set(key,{...x,protocol:x.port===4370?'zk':x.port===8000?'hikvision':'http',name:x.port===4370?'ZK-compatible biometric device':x.port===8000?'Hikvision candidate':'HTTP biometric device',source:'LAN TCP discovery'});}return [...byIp.values()];}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',x=>s+=x);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});});}
function clean(s){return String(s??'').replace(/\u0000/g,'').trim();}
function arabicCount(s){return (String(s).match(/[\u0600-\u06ff]/g)||[]).length;}
function printableCount(s){return (String(s).match(/[\x20-\x7e\u0600-\u06ff]/g)||[]).length;}
function decodeZkField(buf){const b=Buffer.from(buf);let end=b.indexOf(0);const raw=end>=0?b.subarray(0,end):b;if(!raw.length)return '';const candidates=[];const add=(label,text)=>{text=clean(text);if(text)candidates.push({label,text});};add('utf8',raw.toString('utf8'));add('utf16le',raw.toString('utf16le'));try{add('win1256',new TextDecoder('windows-1256').decode(raw));}catch{}add('latin1',raw.toString('latin1'));add('ascii',raw.toString('ascii'));const best=candidates.sort((a,b)=>{const score=x=>arabicCount(x.text)*100+printableCount(x.text);return score(b)-score(a)})[0];return best?.text||'';}
function decodeZkUser(raw){const b=Buffer.from(raw);return {uid:b.readUIntLE(0,2),name:decodeZkField(b.subarray(11,35)),cardno:String(b.readUIntLE(35,4)),userId:decodeZkField(b.subarray(48,57)),role:b.readUIntLE(2,1)};}
function parseRawUsers(data){const b=Buffer.from(data);let p=0;if(b.length>=4){const possible=b.readUIntLE(0,4);if(possible>0&&possible<=b.length-4)p=4;}const out=[];for(;p+72<=b.length;p+=72){const u=decodeZkUser(b.subarray(p,p+72));if(u.userId||u.name||u.uid)out.push(u);}return out;}
function dateFromZkTime(v){const second=v%60;v=(v-second)/60;const minute=v%60;v=(v-minute)/60;const hour=v%24;v=(v-hour)/24;const day=v%31+1;v=(v-(day-1))/31;const month=v%12;const year=(v-month)/12+2000;const d=new Date(year,month,day,hour,minute,second);return Number.isNaN(d.getTime())?null:d;}
function parseRawLogs(data){const b=Buffer.from(data);let p=0;if(b.length>=4){const possible=b.readUIntLE(0,4);if(possible>0&&possible<=b.length-4)p=4;}const out=[];for(;p+40<=b.length;p+=40){const r=b.subarray(p,p+40);const userId=decodeZkField(r.subarray(2,11));const stamp=dateFromZkTime(r.readUInt32LE(27));if(stamp)out.push({userId,timestamp:stamp});}return out;}
async function rawZkData(device,request){const result=await device.ztcp.readWithBuffer(request);if(result?.err)throw result.err;if(!result?.data)return Buffer.alloc(0);const data=Buffer.from(result.data);try{await device.ztcp.freeData()}catch{}return data;}
async function openZk(d){let Zkteco;try{({default:Zkteco}=await import('zkteco-js'));}catch{throw new Error('Driver ZKTeco غير مثبت داخل admin-affairs.');}const device=new Zkteco(d.ip,Number(d.port)||4370,10000,10000);await device.createSocket();return device;}
function normalizeUser(u){return {pin:clean(u.userId)||String(u.uid),uid:String(u.uid),name:clean(u.name),card:String(u.cardno||0),userId:clean(u.userId)};}
async function pullZkUsers(d){const device=await openZk(d);try{const raw=await rawZkData(device,ZK_USERS);return parseRawUsers(raw).map(normalizeUser).filter(x=>x.pin||x.name);}finally{try{await device.disconnect()}catch{}}}
async function pullZk(d){const device=await openZk(d);try{const users=parseRawUsers(await rawZkData(device,ZK_USERS));const byKey=new Map();for(const u of users){if(String(u.uid))byKey.set(String(u.uid),u);if(u.userId)byKey.set(clean(u.userId),u);}const logs=parseRawLogs(await rawZkData(device,ZK_ATT));const punches=logs.map(x=>{const user=byKey.get(clean(x.userId));const code=clean(user?.userId)||clean(x.userId)||String(user?.uid||'');if(!code)return null;const d=x.timestamp;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(user?.name),date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};}).filter(Boolean);if(!punches.length&&logs.length)throw new Error('تمت قراءة سجلات ZKTeco لكن لم يتم العثور على رقم مستخدم صالح.');return punches;}finally{try{await device.disconnect()}catch{}}}
function unwrapSdk(result){return Array.isArray(result)?result:(result?.data||result?.users||result?.logs||result?.records||[])}
function sdkUser(raw){return {pin:clean(raw?.userid??raw?.userId??raw?.user_id??raw?.pin??raw?.id),uid:String(raw?.uid??raw?.userSn??''),name:clean(raw?.name??raw?.userName??raw?.username),card:String(raw?.cardno??raw?.cardNo??raw?.card??'0')}}
function sdkLog(raw){const code=clean(raw?.userid??raw?.userId??raw?.user_id??raw?.pin??raw?.deviceUserId??raw?.device_user_id);const rawDate=raw?.recordTime??raw?.record_time??raw?.attTime??raw?.timestamp??raw?.time??raw?.datetime;const d=rawDate instanceof Date?rawDate:new Date(rawDate);return code&&!Number.isNaN(d.getTime())?{userId:code,timestamp:d}:null}
async function pullZkUsers(d){const device=await openZk(d);try{return unwrapSdk(await device.getUsers()).map(sdkUser).filter(x=>x.pin||x.name)}finally{try{await device.disconnect()}catch{}}}
async function pullZk(d){const device=await openZk(d);try{const users=unwrapSdk(await device.getUsers()).map(sdkUser),logs=unwrapSdk(await device.getAttendances()).map(sdkLog).filter(Boolean),byKey=new Map();users.forEach(u=>{if(u.pin)byKey.set(clean(u.pin),u);});return logs.map(x=>{const u=byKey.get(clean(x.userId)),code=clean(u?.pin)||clean(x.userId);if(!code)return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(u?.name),date:x.timestamp.toISOString().slice(0,10),time:x.timestamp.toTimeString().slice(0,5)}}).filter(Boolean)}finally{try{await device.disconnect()}catch{}}}
async function testZk(d){try{const device=await openZk(d);try{const raw=await rawZkData(device,ZK_USERS);const users=parseRawUsers(raw);return {ok:true,message:`تم الاتصال وقراءة ${users.length} مستخدم فعليًا عبر ZKProtocol.`};}finally{try{await device.disconnect()}catch{}}}catch(e){return {ok:false,message:'فشل اتصال ZKProtocol: '+(e instanceof Error?e.message:String(e))};}}
async function pullGenericHttp(d){const protocol=Number(d.port)===443||Number(d.port)===8443?'https':'http';const base=protocol+'://'+d.ip+':'+(Number(d.port)||80);const paths=['/api/attendance','/api/records','/ISAPI/AccessControl/AcsEvent'];const auth=d.username?Buffer.from(String(d.username)+':'+String(d.password||'')).toString('base64'):'';for(const path of paths){try{const r=await fetch(base+path,{headers:auth?{Authorization:'Basic '+auth}:{}});if(!r.ok)continue;const j=await r.json();const arr=j.records||j.data||j.Attendance||j.AcsEvent?.InfoList||[];if(!Array.isArray(arr))continue;return arr.map(x=>{const code=clean(x.code??x.pin??x.user_id??x.employeeNoString??x.employeeNo);const dt=new Date(x.datetime??x.timestamp??x.time??x.dateTime??'');if(!code||Number.isNaN(dt.getTime()))return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(x.name??x.user_name),date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5)};}).filter(Boolean);}catch{}}throw new Error('لم يتم التعرف على API قياسي لهذا الجهاز');}
async function pullHik(d){const auth=Buffer.from(String(d.username||'')+':'+String(d.password||'')).toString('base64');const now=new Date(),start=new Date(now.getTime()-7*86400000);const url='http://'+d.ip+':'+(Number(d.port)||80)+'/ISAPI/AccessControl/AcsEvent?format=json';const payload={AcsEventCond:{searchID:crypto.randomUUID(),searchResultPosition:0,maxResults:1000,major:5,minor:0,startTime:start.toISOString(),endTime:now.toISOString()}};const r=await fetch(url,{method:'POST',headers:{Authorization:'Basic '+auth,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Hikvision HTTP '+r.status);const j=await r.json();const list=j?.AcsEvent?.InfoList||j?.AcsEvent?.AcsEventInfo||[];return (Array.isArray(list)?list:[list]).map(x=>{const code=clean(x.employeeNoString??x.employeeNo),dt=new Date(x.time||x.dateTime||'');if(!code||Number.isNaN(dt.getTime()))return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(x.name),date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5)};}).filter(Boolean);}
async function testDevice(d){if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))return testZk(d);const ok=await tcpOpen(d.ip,Number(d.port)||80,1200);return {ok,message:ok?'منفذ الجهاز متاح':'منفذ الجهاز غير متاح'};}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS')return json(res,204,{});if(u.pathname==='/api/fingerprint/health')return json(res,200,{ok:true,port:PORT});if(u.pathname==='/api/fingerprint/discover')return json(res,200,{devices:await discover(u.searchParams.get('port'))});if(u.pathname==='/api/fingerprint/test'){const r=await testDevice({ip:u.searchParams.get('ip'),port:Number(u.searchParams.get('port')||4370),protocol:u.searchParams.get('protocol')||'auto'});return json(res,r.ok?200:502,r);}if(u.pathname==='/api/fingerprint/users'&&req.method==='POST'){const d=await body(req);if(!d?.ip)throw new Error('device is required');if(d.protocol==='zk'||d.protocol==='auto')return json(res,200,{users:await pullZkUsers(d)});throw new Error('استيراد المستخدمين متاح حاليًا لـ ZKTeco');}if(u.pathname==='/api/fingerprint/pull'&&req.method==='POST'){const d=await body(req);let punches=[];if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))punches=await pullZk(d);else if(d.protocol==='hikvision')punches=await pullHik(d);else if(d.protocol==='http'||d.protocol==='auto')punches=await pullGenericHttp(d);else throw new Error('لا يوجد Driver لهذا البروتوكول حتى الآن');return json(res,200,{punches,count:punches.length});}return json(res,404,{message:'Not found'});}catch(e){return json(res,500,{ok:false,message:e instanceof Error?e.message:String(e)})}});
server.listen(PORT,HOST,()=>console.log(`Fingerprint Gateway listening on http://${HOST}:${PORT}`));
