name: Diagnose App syntax
on:
  push:
    branches: [main]
jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Build
        working-directory: admin-affairs
        run: npm install && npm run build
